stages:
    - build
    - test
    - deploy

before_script:
     - export GRADLE_USER_HOME='pwd'/.gradle
     - chmod +x ./gradlew

build:
    image: gradle:alpine
    stage: build
    script: 
        - ./gradlew assemble
    tags:
        - grad

test: 
    stage: test 
    script:
        - ./gradlew check
    tags:
        - grad

deploy:
    stage: deploy
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev 
        - gem install dpl
        - echo $HEROKU_APPNAME
        - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    only:
        - master
    tags:
        - dalfcs_gitlab_docker_ci
